version: '3'
services:
  softy-pinko-back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile

  softy-pinko-front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - softy-pinko-front-end
      - softy-pinko-back-end